### ISSUE TITLE
[bionic] install hook fails on missing package python3-pip

### ISSUE THREAD

**Issue by ryan-beisner** [juju-solutions/layer-basic#113]
When using layer-basic on Bionic, we see install hook failures on missing package python3-pip.  A manual post-deployment ```sudo apt-get update``` resolves this, indicating that perhaps the package is trying to be installed before the index is updated.

Reference:

https://bugs.launchpad.net/charm-aodh/+bug/1765212

**Comment by johnsca** [comment]
I wonder why `python3-pip` isn't in the index cached in the image?  I think that cloud-init or Juju used to do an `apt update` automatically but it was removed for performance reasons.  I'm a little wary of adding back in an unconditional `apt update` to this layer, as it would potentially be a performance hit for all charms, especially for the ones that add sources and would end up having to do multiple `apt update`s.  We're already installing pip via apt and then turning around and updating it via pip to the bundled version to get some bug fixes for the wheelhouse management; I wish there were a way we could just directly install the bundled copy directly.

@marcoceppi Do you by chance recall the discussions around whether or not charms should always be doing an `apt update` first off?

**Comment by maaudet-ca** [comment]
I'm having the same issue. Although it's not consistent as for the same bundle it may happen to about 35% of the machines. 

Also, I only saw this issue (so far) on LXD containers in AWS machines on the AWS cloud.

**Comment by Cynerva** [comment]
There seems to be a race lurking somewhere in all this. Deploying the following bundle (on `aws/us-east-1`) has been, by far, the most reliable way for me to reproduce the issue:

```
machines:
  '0':
    constraints: cores=2
  '1':
    constraints: cores=2
services:
  ubuntu:
    charm: cs:ubuntu
    num_units: 3
    to:
    - '0'
    - 'lxd:0'
    - 'lxd:1'
```

Most of the time, this results in a successful deployment to 0/lxd/0 and a failed deployment to 1/lxd/0:
```
Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  active    idle   0        34.201.10.111          ready
ubuntu/1   active    idle   0/lxd/0  252.75.188.64          ready
ubuntu/2   error     idle   1/lxd/0  252.51.168.182         hook failed: "install"
```

On units that succeed, I see an `apt-get dist-upgrade` (note that `apt-get update` would not be shown here):
```
$ sudo cat /var/log/apt/history.log | grep Commandline
Commandline: apt-get --purge remove --assume-yes ^linux-.* linux-base+
Commandline: apt-get --purge remove --assume-yes ^grub-.*
Commandline: /usr/bin/apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet dist-upgrade
Commandline: /usr/bin/apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install curl cpu-checker bridge-utils cloud-utils tmux ubuntu-fan
Commandline: apt-get --option=Dpkg::Options::=--force-confold --assume-yes install python3-pip python3-setuptools python3-yaml python3-dev
```

On units that fail, I don't see the dist-upgrade:
```
$ sudo cat /var/log/apt/history.log | grep Commandline
Commandline: apt-get --purge remove --assume-yes ^linux-.* linux-base+
Commandline: apt-get --purge remove --assume-yes ^grub-.*
Commandline: /usr/bin/apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install curl cpu-checker bridge-utils cloud-utils tmux ubuntu-fan
```

I'm guessing that the Juju agent normally does an `apt-get update` and `apt-get dist-upgrade` before running the charm hooks (assuming that the corresponding model configs, `enable-os-refresh-update` and `enable-os-upgrade`, are enabled). Seems like they're getting skipped or run out of order.

**Comment by maaudet-ca** [comment]
It's probably skipped because a `juju resolved` doesn't fix the issue. I have to go on the LXD containers and run `apt update` manually. The weird part is that it doesn't happen on xenial, only on bionic. I wonder what creates the difference in the images.

**Comment by johnsca** [comment]
Does it actually require `dist-upgrade` or would `update` be sufficient.  The latter seems like a safer approach.

**Comment by johnsca** [comment]
The k8s charms in edge should be updated with this fix.  @CalvinHartwell Please let me know if you still have any issues.
