### ISSUE TITLE
Using PATH folders cause race conditions between charms

### ISSUE THREAD

**Issue by phvalguima** [juju-solutions/layer-basic#136]
Suppose a real scenario where we have a main application (e.g. kubernetes-master) with multiple subordinates. In this context, if multiple subordinates are using layer-basic, but built with different versions of that layer; we may see inconsistent environment across nodes under same application.

So, deploying kubernetes-master + calico such as: https://pastebin.canonical.com/p/tZ88Qj8jvt/

In this case, some nodes ended up with most recent charm-env script: https://github.com/juju-solutions/layer-basic/blob/master/bin/charm-env and Calico deployed correctly
However, other nodes finish with charm-env script such as: https://github.com/juju-solutions/layer-basic/blob/1e25cf7d63285f222207efb4b189f8c076b78b2d/bin/charm-env and Calico charm is stuck on waiting.

Using same folders (e.g. $PATH) for multiple charms which carry multiple versions of same scripts will cause race-condition situations

**Comment by Cynerva** [comment]
To clarify, the calico charm includes and depends on https://github.com/juju-solutions/layer-basic/pull/123, but other subordinates in the same deployment do not include it. There is a race over which version of charm-env gets written to `/usr/local/sbin/charm-env`.
