### ISSUE TITLE
Wheelhouse includes Jinja2<=2.10.1 but charmhelpers requires 2.11

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-basic#155]
Since commit https://github.com/juju/charm-helpers/commit/2e658428af861bb3c91fc60d45e26ca38f4f79c9 we need 2.11 in order to install/upgrade charms but the wheelhouse.txt in layer-basic specifies Jinja2<=2.10.1.

Not sure if this is simply that weelhouse.txt needs an update, or if charmhelpers needs a fix, will report in both places.

**Comment by auria** [comment]
I've updated the issue filed in the charm-helpers project https://github.com/juju/charm-helpers/issues/433

This is a clash between "charm build" generated wheelhouse/* tarballs (Jinja2-2.10.1.tar.gz) and what charm-helpers expects at runtime in Trusty and Xenial (Jinja2==2.11).

A fix has been suggested at https://github.com/juju/charm-helpers/pull/434

**Comment by xavpaice** [comment]
the release of charm-helpers 0.20.10 includes this fix - thanks for the swift response!
