### ISSUE TITLE
Charm Dependency Checks during install hook fail when pip3 has git revision package

### ISSUE THREAD

**Issue by afreiberger** [juju-solutions/layer-basic#182]
_load_installed_versions fails if pip freeze command contains a line without '=='.

When installing a charm to a host where "project" egg has been installed via git repo, the install hook fails.

unit-telegraf-0: 17:28:27 DEBUG juju.worker.uniter.runner starting jujuc server  {unix @/var/lib/juju/agents/unit-telegraf-0/agent.socket <nil>}
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install Traceback (most recent call last):
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install   File "/var/lib/juju/agents/unit-telegraf-0/charm/hooks/install", line 8, in <module>
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install     basic.bootstrap_charm_deps()
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install   File "lib/charms/layer/basic.py", line 127, in bootstrap_charm_deps
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install     _load_installed_versions(vpip)
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install   File "lib/charms/layer/basic.py", line 255, in _load_installed_versions
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install     pkg, ver = pkg_ver.split('==')
unit-telegraf-0: 17:28:28 DEBUG unit.telegraf/0.install ValueError: not enough values to unpack (expected 2, got 1)
unit-telegraf-0: 17:28:29 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1

pip freeze |grep -v == shows:

$ pip3 freeze |grep -v ==
-e git+git+ssh://git.launchpad.net/project@000111222333444555666777888999#egg=project&subdirectory=project

$ pip3 list|grep project
project (2.5.1+git.14.00011122, /home/ubuntu/my/project)

I would recommend that we check if the line contains == before trying to split on it, and if it doesn't contain ==, we should either not register the package (as it's likely a personal package not related to the charm), or call pip list to determine the revision for that package.

Of course, another workaround would be for all charms to have use_system_packages=false.

**Comment by afreiberger** [comment]
Specifically this is related to "editable package installs" when you've 'pip3 install -e ./path/to/my/project' the pip freeze output is not package==version.

A workaround if you run iinto this is to move the project.egg-info directory out of the way, let the charm resolve, then move the project.egg-info directory back into place.

cd /home/myuser/myproject/
egg=$(ls *.egg-info)
mv $egg ${egg}.bak
juju resolved $unit
# wait for settled model
mv ${egg}.bak $egg

**Comment by johnsca** [comment]
Yeah, I think we could reasonably skip anything that doesn't match the form we expect since the only reason this parsing is used is to determine whether any of the wheelhouse packages need to be updated, and those could never be installed as editable.  That said, I would **strongly** recommend that charms have both `use_venv: true` and `include_system_packages: false`, and that is doubly true for subordinates like telegraf.  That provides much more reliable encapsulation for the charm, and they have been the default for some time now.

**Comment by afreiberger** [comment]
Thanks, @johnsca.  I've opened a bug against telegraf to change it's encapsulation for future safety as well.

**Comment by addyess** [comment]
i worked around the issue by changing the layer/basic.py

``` diff
diff --git a/lib/charm/layer/basic.py b/lib/charm/layer/basic.py
--- a/lib/charm/layer/basic.py
+++ b/lib/charm/layer/basic.py
@@ -1,255 +1,255 @@
-        pkg, ver = pkg_ver.split('==')
+        pkg, ver = pkg_ver.split('==') if '==' in pkg_ver else (pkg_ver, '0.0.0')
```

```diff
```
