### ISSUE TITLE
layer-basic fails to install wheelhouse on hirsute due to pip 21 dependency resolution

### ISSUE THREAD

**Issue by ajkavanagh** [juju-solutions/layer-basic#194]
(Note this is fixed by the PR: #193)

pip 21+ fails to install the wheelhouse on hirsute as, despite all the versions being available, it thinks that the bare 'name' of the package can't resolve through to the versions provided in the wheelhouse.  Thus you get perverse errors where it says it wants a version but it's not available, despite being the one in the wheelhouse.

A solution is to put the versions back on the package names such that the pip install command becomes:

```
pip install .... package=version package2=version2
```

**Comment by AurelienLourot** [comment]
Fixed by #193 - can be closed (I don't have permissions)

**Comment by ajkavanagh** [comment]
Thanks Aurelien for the confirmation.
