### ISSUE TITLE
Layer options need a CLI

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-basic#34]
There's no way to use layer options in bash layers currently, because the parsing code is Python only.  We need to expose a CLI for layer options.  This can either be a script in the base layer, or maybe we want to split layer options out into a separate library pulled in via the wheelhouse (or into reactive?) so that it can use the `setup.py` tools for registering a CLI.

**Comment by galgalesh** [comment]
Closed by https://github.com/juju-solutions/layer-basic/commit/f8cdda72e56e4558c7b4759d2e3372e65030170c
