### ISSUE TITLE
Automatic upgrading

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/layer-basic#39]
Juju Charms should promote best-practices and have sane and production-ready defaults. Turning on automatic updates seems to a good way to ensure security. Do you think this is something we should be doing in the base layer, so all Charms have this automatically?

What do you think?

to be clear: I'm talking about upgrades system packages using apt.

**Comment by stub42** [comment]
I think this should go in a higher layer, such as an Ubuntu layer or the existing apt layer. Otherwise we need platform specific code in the base layer to cope with Windows, CentOS etc.

**Comment by galgalesh** [comment]
Automatic upgrades are enabled by default for 16.04, so I'm closing this.
