### ISSUE TITLE
Missing base hooks: leadership, update-status, storage

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/layer-basic#4]
New hooks exist since 1.23 of Juju which are not modeled in the base layer:

* leader-elected
* leader-settings-changed
* {storage}-storage-attached
* {storage}-storage-detaching
* update-status

where `{storage}` is defined under the top level `storage` key in metadata.yaml

It'd be great to have them there by default

**Comment by chuckbutler** [comment]
+1 to this

Missing update-status, and upgrade-charm hooks leave me with reactive charms that don't respond properly when decorating with @hook() decorators, as the hook exits 0 - never reaching the proper hook context in the reactive methods.

**Comment by marcoceppi** [comment]
Would it be possible for charm build to sniff all @hook decorators and add
hooks that are in a whitelist that wouldn't be added by default?

**Comment by johnsca** [comment]
Not really, because of the external / non-python handlers; it's not really possible to introspect them.

I should perhaps clarify that I'm not entirely adverse to including `update-status`  by default, but we would just need to make sure we call it out as a consideration in the docs.

**Comment by johnsca** [comment]
juju-solutions/reactive-base-layer#12
juju/charm-tools#67
juju-solutions/reactive-base-layer#13

**Comment by johnsca** [comment]
These are all available now.
