### ISSUE TITLE
Base Layer has an aggressive license

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-basic#47]
GPL-3 on the base layer is a pretty aggressive license. It was suggested we look into LGPL or a slightly less aggressive license for users building on top of the base layer.

Thread originated in layer-logstash, where i looked at the base layer and copied its license, figuring derived works should be of similar license.

https://github.com/juju-solutions/layer-logstash/pull/11

**Comment by galgalesh** [comment]
Fixed in https://github.com/juju-solutions/layer-basic/commit/59bba09a52e11cac3bf2738efd1a1cb497ecbcf9#diff-2ae41fa6dbd644a6846389ad14167167
