### ISSUE TITLE
basic layer should pull in apt layer

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/layer-basic#78]
I think the apt layer should be pulled into the basic layer and reduce the number of ways to install packages and react on them. This would effectively get rid of an additional layer that tends to be included in all charm anyway

**Comment by johnsca** [comment]
Originally, the apt layer would be too late to install some packages, but now with `exec.d/preinstall` support, it would be feasible to move that functionality out to the apt layer.  However, I'd actually prefer to keep that functionality in a separate apt layer and trim down the basic layer as much as possible.

**Comment by galgalesh** [comment]
I agree that the basic layer should be as thin as possible. There are also many requests to make the base layer cross-platform. Pulling in the apt layer only makes that harder. Closing this issue for now. Please reopen if you feel additional discussion is needed.
