### ISSUE TITLE
Config options without defaults never get removed from config.changed.x

### ISSUE THREAD

**Issue by simonklb** [juju-solutions/layer-basic#79]
I think the problem originates from init_config_states() grabbing all of the config options from the yaml file while clear_config_states() only looks at hookenv.config(). Since hookenv.config() does not include the --all flag when executing the config-get command the options without a default are not included. That, and also due to the fact that config options are always changed when they have no previous value.

**Comment by cmars** [comment]
I believe this might be the root cause: https://bugs.launchpad.net/charm-helpers/+bug/1630706

**Comment by simonklb** [comment]
I'm not sure. Looking at https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/basic.py#L155 that would remove the config.changed.x state. In my case the config.changed.x state is active even though I've never changed the option.

**Comment by simonklb** [comment]
For anyone that stumble upon this or is involved - I've added a fix proposal here: https://code.launchpad.net/~simonklb/charm-helpers/include-empty-config-options

**Comment by simonklb** [comment]
Fix is released in charmhelpers 0.10.0
