### ISSUE TITLE
enable travis for this repo

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-basic#89]
I'm not sure if the inclusion of a `.travis.yml` in this layer would adversely affect upper layers, but it sure would be nice to at least have travis lint commits to this repo.

**Comment by marcoceppi** [comment]
I don't think it's problematic - worst case scenario add it to the excludes

**Comment by johnsca** [comment]
:+1: I don't see it causing any issue, either, since Travis integration has to be manually enabled per repo.

**Comment by kwmonroe** [comment]
I was mostly concerned with how the `.travis.yml` might conflict with upper layers -- ie, would it get merged wonkily on `charm build`?  The answer is apparently "no, it doesn't get merged", so i'm less worried now.

**Comment by johnsca** [comment]
This was done as part of #135
