### ISSUE TITLE
centos support issue

### ISSUE THREAD

**Issue by zhougit86** [juju-solutions/layer-basic#93]
Hi All,

I am trying to deploy charms(the charm is using the reactive python and included layer-basic) on Centos machine, the juju status showing error

I ssh to the juju-machine in which I was deploying, I found some errors installing python3. then I installed python34 manually and restarted the jujud. Then I found the apt-get failure. so I checked the basic.py in this project. there was apt-get in this project.

I did build the charm using charm build -s centos7.   but the problem is still there. Can anyone tell me whether I should try another way to build the charm or wait for a updated version to fix this issue?

**Comment by galgalesh** [comment]
Progress on CentOS7 support is tracked here: #97

Afaik, no-one is actively working on it currently, but we welcome contributions for this.
