### ISSUE TITLE
Enable support for CentOS7

### ISSUE THREAD

**Issue by fengxia41103** [juju-solutions/layer-basic#97]
Many lines in layer-basic are coded to have Python3 and Ubuntu in mind.

I'm working on a project in which we want to build charms for CentOS7. Through my tests there are four areas to change to make layer-basic Python27 compatible:

1. Using python2 modules, eg python-setuptools.
2. Set the correct binary path for your pip.
3. Use platform.linux_distribution()[0] to determine host platform.
4. apt uses --assume-yes, where yum uses --assumeyes.

For Python3 related lines, we can improve it further by detecting the Python version being used and installing packages accordingly.

**Comment by galgalesh** [comment]
Hi @fengxia41103 

We'd love to have official support for Centos7! Afaik, this isn't on our roadmap any time soon but feel free to create a PR if you implement some of the fixes you're proposing.

If we ever get full CentOS compatibility, we should look at making CentOS part of [the integration tests of `charms.reactive`](https://github.com/juju-solutions/charms.reactive/blob/master/tests/integration.sh) so we don't break it again in the future.

**Comment by johnsca** [comment]
This was done in #148
