### ISSUE TITLE
basic.py does not support centos7.    

### ISSUE THREAD

**Issue by john-cplanenetworks** [juju-solutions/layer-basic#99]
required to check OS and support yum on centos7

--- error when deploying on centos7 --- 
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected Traceback (most recent call last):
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "/var/lib/juju/agents/unit-rac-master-0/charm/hooks/leader-elected", line 8, in <module>
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     basic.bootstrap_charm_deps()
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "lib/charms/layer/basic.py", line 55, in bootstrap_charm_deps
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     'python3-dev',
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "lib/charms/layer/basic.py", line 163, in apt_install
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     check_call(cmd + packages, env=env)
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "/usr/lib64/python3.4/subprocess.py", line 553, in check_call
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     retcode = call(*popenargs, **kwargs)
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "/usr/lib64/python3.4/subprocess.py", line 534, in call
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     with Popen(*popenargs, **kwargs) as p:
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "/usr/lib64/python3.4/subprocess.py", line 856, in __init__
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     restore_signals, start_new_session)
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected   File "/usr/lib64/python3.4/subprocess.py", line 1460, in _execute_child
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected     raise child_exception_type(errno_num, err_msg)
unit-rac-master-0: 23:01:14 INFO unit.rac-master/0.leader-elected FileNotFoundError: [Errno 2] No such file or directory: 'apt-get'

-----  fix should be at least here - check for centos and calll yum 
def apt_install(packages):
    """
    Install apt packages.

    This ensures a consistent set of options that are often missed but
    should really be set.
    """
    if isinstance(packages, (str, bytes)):
        packages = [packages]

    env = os.environ.copy()

    if 'DEBIAN_FRONTEND' not in env:
        env['DEBIAN_FRONTEND'] = 'noninteractive'

    cmd = ['apt-get',
           '--option=Dpkg::Options::=--force-confold',
           '--assume-yes',
           'install']
    for attempt in range(3):
        try:
            check_call(cmd + packages, env=env)
        except CalledProcessError:
            if attempt == 2:  # third attempt
                raise
            sleep(5)
        else:
            break

**Comment by galgalesh** [comment]
Progress on CentOS7 support is tracked here: https://github.com/juju-solutions/layer-basic/issues/97

Afaik, no-one is actively working on it currently, but we welcome contributions for this.
